### ISSUE TITLE
Comments on `install_reqs.yml`

### ISSUE THREAD

**Issue by mj-will** [icg-gravwaves/lisa_premerger_paper#1]
Suggestions

- Remove the `default` channel
- Add the `pytorch` channel
- Add the following packages (for nessai):
    - `torch`
    - `cpuonly`
    - `nessai`
    - `jupyter`/`ipykernel`
 - Consider installing the specific branch of nessai in the yaml file directly using: `git+https://github.com/mj-will/nessai.git@pre-merger-mcmcflowproposal` (same for PyCBC?)

**Comment by GarethCabournDavies** [comment]
Ugh, thought id done these already. I have done in my local version, but not committed yet

**Comment by GarethCabournDavies** [comment]
I think `install_reqs.yml` is good now? If so, please close
It works as it is for generating all analyses and plotting
